services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: roshan
      POSTGRES_USER: roshan
      POSTGRES_PASSWORD: roshan

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=True

  redis:
    image: "redis:latest"

  celery-worker:
    build: .
    command: celery -A technews worker
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A technews beat
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  flower:
    image: mher/flower:latest
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery-worker

volumes:
  postgres_data:
