services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: roshan
      POSTGRES_USER: roshan
      POSTGRES_PASSWORD: roshan

  redis:
    image: redis:7

  web:
    build: .
    command: gunicorn technews.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery-worker:
    build: .
    command: celery -A technews worker
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A technews beat
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  flower:
    image: mher/flower:1.2.0
    command: flower --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery-worker

volumes:
  postgres_data:
